# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-CTA-STang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-CTA-STang
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'

  target 'iOS-CTA-STangTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
